### ISSUE TITLE
Will Kanji decks be made available for Genki 2?

### ISSUE THREAD

**Issue by cooperwalbrun** [mi-ael/genkikani#1]
@mi-ael Do you have any plans to create a similar Kanji deck for Genki 2 (3rd edition)?

**Comment by mi-ael** [comment]
Yes, I actually have plans to extend this deck to Genki 2 sometime in the next 30 days. If you are interested in supporting my effort (and thus speeding it up a bit), you can to take a look at the data files (eg. [https://github.com/mi-ael/genkikani/blob/master/data/genki/kanjis_12.yaml](https://github.com/mi-ael/genkikani/blob/master/data/genki/kanjis_12.yaml) ) and create new yaml files just like that with the kanjis and vocabulary from Genki 2 and create a pull request.

**Comment by mi-ael** [comment]
Live got in the way and I ended up not doing what I said in the last comment
